In [1]:
import pandas as pd
import numpy as np


In [14]:
from sklearn.datasets import load_iris
data=load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)

In [31]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [32]:
df['target']=data.target

In [33]:
df['target'].value_counts()

2    50
1    50
0    50
Name: target, dtype: int64

In [34]:
X=df.drop('target',axis=1)
y=df['target']
ss=StandardScaler()
standX=ss.fit_transform(X)

In [39]:
model=LogisticRegression(multi_class='ovr')
model.fit(standX,y)
print(model.score(standX,y))

0.9266666666666666


In [42]:
(model.intercept_,model.coef_)

(array([-1.61861686, -0.89769778, -2.70851029]),
 array([[-0.81016631,  1.39369878, -1.68738578, -1.51899135],
        [ 0.13037985, -1.2463382 ,  0.78919477, -0.88943988],
        [ 0.01299039, -0.1445346 ,  1.86317337,  2.69887272]]))

In [47]:
np.round(model.predict_proba(standX)[:10],2)

array([[0.91, 0.09, 0.  ],
       [0.75, 0.24, 0.  ],
       [0.84, 0.16, 0.  ],
       [0.79, 0.21, 0.  ],
       [0.93, 0.07, 0.  ],
       [0.97, 0.03, 0.  ],
       [0.9 , 0.1 , 0.  ],
       [0.88, 0.12, 0.  ],
       [0.73, 0.27, 0.  ],
       [0.77, 0.23, 0.  ]])

In [51]:
#do OVR by hand
from sklearn.preprocessing import label_binarize

In [55]:
y_bin=label_binarize(y,model.classes_)
model.classes_

array([0, 1, 2])

In [58]:
model_class={}
for i in model.classes_:
    model_class[i]= LogisticRegression(solver='liblinear')
    model_class[i].fit(standX,y_bin[:,i])
    print(model_class[i].coef_)
    print('Same as OVR?',np.allclose(model_class[i].coef_,model.coef_[i,:]))

[[-0.81016631  1.39369878 -1.68738578 -1.51899135]]
Same as OVR? True
[[ 0.13037985 -1.2463382   0.78919477 -0.88943988]]
Same as OVR? True
[[ 0.01299039 -0.1445346   1.86317337  2.69887272]]
Same as OVR? True


In [72]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,precision_score
preds=model.predict(standX)
np.allclose(model.score(standX,y),accuracy_score(y,preds))

True

In [65]:
confusion_matrix(y,preds)

array([[50,  0,  0],
       [ 0, 43,  7],
       [ 0,  4, 46]])

In [67]:
print(classification_report(y,preds))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.91      0.86      0.89        50
          2       0.87      0.92      0.89        50

avg / total       0.93      0.93      0.93       150



In [71]:
43/(43+4)

0.9148936170212766

In [75]:
precision_score(y,preds,average='weighted')

0.9276060484410544